export const defaultHostPluginIds = Object.freeze({
  application: "official.application",
  configurationDiscovery: "official.configuration-discovery",
  configurationParser: "official.configuration-parser",
  kernel: "official.kernel",
  model: "official.model",
  persistence: "official.persistence",
  projection: "official.projection",
  queryEngine: "official.query-engine",
  resources: "official.resources",
  surface: "official.surface",
  typescript: "official.typescript",
});

export const defaultHostCapabilityIds = Object.freeze({
  configurationDiscovery: "groma.configuration-discovery/v1",
  configurationParser: "groma.configuration-parser/v1",
  graph: "groma.graph/v1",
  invariant: "groma.invariant/v1",
  model: "groma.model/v1",
  operations: "groma.operations/v2",
  projection: "groma.projection-index/v1",
  projectionRead: "groma.projection-read/v1",
  queryEngine: "groma.graph-query/v2",
  queries: "groma.queries/v1",
  resourceMapper: "groma.resource-mapper/v1",
  resources: "groma.resources/v1",
  snapshotStateDecoder: "groma.snapshot-state-decoder/v1",
  store: "groma.intent-store/v1",
  surface: "groma.host-surface/v1",
  transactionEngine: "groma.transaction-engine/v1",
  transactionProvider: "groma.transaction-provider/v1",
  workspace: "groma.workspace/v1",
});
